"""Extract the SkyNET pickup / destruction / ambient-sound tables from
Skynet.exe into godot_project/scripts/pickup_data.gd.

Sources (Skynet.exe LE image, file offset = VA + 0x538A4, data pointers
are stored relative to 0x30000; all traced in docs/implementation_plan.md
section M):
  item table       VA 0x35800, 32-byte records {sprite, pool, amount,
                   heal %, armor (16.16), weapon, callback, message id};
                   FUN_0011d600 gives every map sprite listed here act
                   0xFD at map start, handler 0x11d670 applies it.
  drop lists       VA 0x42b7e: 10 pointers -> {count, u16 choices[]}
                   (FUN_00124119 picks one at random, 0 = nothing).
  destruction      VA 0x423d6, 14-byte records {4 x effect sprite,
                   spread, drop type, sound (-2 = random 33..36)};
                   indexed by link record byte 0 (FUN_00123fbd).
  ambient sounds   VA 0x4cc00, {sprite, sound id} pairs until -1;
                   FUN_0012a400 gives matching sprites act 0xEE.
Run from the repo root:  python godot_project/tools/gen_pickup_data.py
"""
import struct

exe = open('Skynet.exe', 'rb').read()
BASE = 0x30000

def fo(va):
    return va + 0x538A4

def i32(va):
    return struct.unpack_from('<i', exe, fo(va))[0]

def i16(va):
    return struct.unpack_from('<h', exe, fo(va))[0]

def u16(va):
    return struct.unpack_from('<H', exe, fo(va))[0]

# STRINGS.PRS keys in the order the message ids are assigned.
MSG_KEYS = {
    24050: 'Str_50cal', 24060: 'Str_GLaunch', 24072: 'Str_LCann', 24082: 'Str_LRifle',
    24093: 'Str_Machine', 24105: 'Str_PprCann', 24117: 'Str_PprMed', 24128: 'Str_PprSml',
    24139: 'Str_RLaunch', 24151: 'Str_Shotgun', 24163: 'Str_Uzi', 24171: 'Str_Bullet',
    24182: 'Str_Bullets', 24194: 'Str_Canister', 24207: 'Str_Satchel', 24219: 'Str_Molotov',
    24231: 'Str_Grenade', 24243: 'Str_Grenades', 24256: 'Str_EnergyB', 24268: 'Str_EnergyC',
    24280: 'Str_Rocket', 24291: 'Str_Rockets', 24303: 'Str_Shell', 24313: 'Str_Pipe',
    24322: 'Str_Health1', 24334: 'Str_Health2', 24346: 'Str_Health3', 24358: 'Str_Health4',
    24370: 'Str_Armor1', 24381: 'Str_Armor2', 24392: 'Str_Armor3', 24403: 'Str_Armor4',
}

items = []
for i in range(64):
    r = struct.unpack_from('<8i', exe, fo(0x35800 + 0x20 * i))
    if r[0] <= 0:
        break
    items.append((r[0], r[1], r[2], r[3], r[4], r[5], MSG_KEYS.get(r[7], '')))

drops = []
for i in range(10):
    p = i32(0x42b7e + 4 * i)
    if p == 0:
        drops.append([])
        continue
    rec = p + BASE
    cnt = i32(rec)
    drops.append([u16(rec + 4 + 2 * k) for k in range(cnt)])

destruct = []
for i in range(140):
    r = struct.unpack_from('<4H3h', exe, fo(0x423d6 + 14 * i))
    destruct.append([[x for x in r[:4] if x != 0], r[4], r[5], r[6]])

ambient = []
va = 0x4cc00
while True:
    s, snd = i32(va), i32(va + 4)
    if s <= 0:
        break
    ambient.append((s, snd))
    va += 8

def gd(v):
    if isinstance(v, str):
        return '"%s"' % v
    if isinstance(v, (list, tuple)):
        return '[' + ', '.join(gd(x) for x in v) + ']'
    return str(v)

out = []
out.append('## GENERATED by godot_project/tools/gen_pickup_data.py from Skynet.exe - do not edit.')
out.append('## Pickup items (table 0x35800), destruction drop lists (0x42b7e),')
out.append('## destruction types (0x423d6) and sprite ambient sounds (0x4cc00).')
out.append('## See docs/implementation_plan.md section M for the semantics.')
out.append('extends RefCounted')
out.append('')
out.append('## sprite index -> [pool, amount, heal %, armor (of 65536), weapon, message key].')
out.append('## pool -1 = none; weapon -1 = none. FUN_0011d600 / handler 0x11d670.')
out.append('const ITEMS: Dictionary = {')
for it in items:
    out.append('\t%d: %s,' % (it[0], gd(list(it[1:]))))
out.append('}')
out.append('')
out.append('## drop type -> sprite choices (one picked at random; 0 = nothing).')
out.append('const DROPS: Array = [')
for d in drops:
    out.append('\t%s,' % gd(d))
out.append(']')
out.append('')
out.append('## destruction type (link record byte 0) -> [effect sprites, spread,')
out.append('## drop type (-1 none), sound id (-1 none, -2 = random 33..36)].')
out.append('const DESTRUCT: Array = [')
for d in destruct:
    out.append('\t%s,' % gd(d))
out.append(']')
out.append('')
out.append('## Sounds of the random-sound destruction choice (-2).')
out.append('const DESTRUCT_RANDOM_SOUNDS: Array = [33, 34, 35, 36]')
out.append('')
out.append('## sprite index -> looping ambient sound id (act 0xEE, FUN_0012a400).')
out.append('const AMBIENT: Dictionary = {')
for s, snd in ambient:
    out.append('\t%d: %d,' % (s, snd))
out.append('}')
open('godot_project/scripts/pickup_data.gd', 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('items', len(items), 'drops', len(drops), 'destruct', len(destruct), 'ambient', len(ambient))
